// import React from "react";
// import {
//     SiBootstrap,
//     SiCss3,
//     SiHtml5,
//     SiGulp,
//     SiGit,
//     SiGithub,
//     SiGrunt,
//     SiGraphql,
//     SiWebpack,
//     SiAngular,
//     SiJavascript,
//     SiNodedotjs,
//     SiNpm,
//     SiTypescript,
//     SiMongodb,
//     SiWordpress,
//     SiWindowsterminal,
//     SiW3C,
//     SiVisualstudiocode,
//     SiShopify,
//     SiSass,
//     SiTailwindcss,
//     SiPython,
//     SiPhp,
//     SiJquery,
//     SiJson,
//   } from "react-icons/si";


// export default Resources [
//     <SiBootstrap />,
//     <SiCss3 />,
//     <SiHtml5 />,
//     <SiGulp />,
//     <SiGrunt />,
//     <SiWebpack />,
//     <SiAngular />,
//     <SiGraphql />,
//     <SiGit />,
//     <SiGithub />,
//     <SiJavascript />,
//     <SiNodedotjs />,
//     <SiNpm />,
//     <SiMongodb />,
//     <SiTypescript />,
//     <SiWordpress />,
//     <SiWindowsterminal />,
//     <SiW3C />,
//     <SiVisualstudiocode />,
//     <SiShopify />,
//     <SiSass />,
//     <SiTailwindcss />,
//     <SiPython />,
//     <SiPhp />,
//     <SiJquery />,
//     <SiJson />,
//   ];
  